### ISSUE TITLE
Pincushion and linearity 

### ISSUE THREAD

**Issue by smdjeff** [english1234/vstcm#8]
https://github.com/english1234/vstcm/blob/8db37865ba3121a6b98a831275f08750b0315600/Teensy%20code/vst_Colour_Mod_v3/drawing.cpp#L377

Some vector games have linearity and pincushion in the deflection board, some are on the game boards.

Consider adding linearity.
Consider making them adjustable values, not just on / off.

**Comment by english1234** [comment]
Thanks for the suggestion Jeff, I've added it to the wiki which contains ideas for future versions. If you want to incorporate the changes yourself, then I'd be happy to integrate them.
